# Generated by Django 5.0.1 on 2026-02-19 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HadithCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Hadith Collection',
                'verbose_name_plural': 'Hadith Collections',
            },
        ),
        migrations.CreateModel(
            name='HadithBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='hadiths.hadithcollection')),
            ],
            options={
                'verbose_name': 'Hadith Book',
                'verbose_name_plural': 'Hadith Books',
                'ordering': ['book_number'],
                'unique_together': {('collection', 'book_number')},
            },
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadith_number', models.CharField(max_length=20)),
                ('arabic_number', models.CharField(blank=True, max_length=20)),
                ('text_arabic', models.TextField(blank=True)),
                ('text_english', models.TextField(blank=True)),
                ('text_swahili', models.TextField(blank=True)),
                ('grades', models.JSONField(blank=True, default=list)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hadiths', to='hadiths.hadithbook')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiths', to='hadiths.hadithcollection')),
            ],
            options={
                'verbose_name': 'Hadith',
                'verbose_name_plural': 'Hadiths',
                'indexes': [models.Index(fields=['hadith_number'], name='hadiths_had_hadith__5df4fa_idx'), models.Index(fields=['collection'], name='hadiths_had_collect_c85e2d_idx'), models.Index(fields=['book'], name='hadiths_had_book_id_56b967_idx')],
                'unique_together': {('collection', 'hadith_number')},
            },
        ),
    ]
