"""Static metadata for all 114 surahs.

Tuple shape: (number, arabic_name, transliteration, english_translation, revelation_type, juz_number)
juz_number is the juz the surah *starts* in.
"""
SURAH_META = [
    (1, 'الفاتحة', 'Al-Fatihah', 'The Opening', 'MECCAN', 1),
    (2, 'البقرة', 'Al-Baqarah', 'The Cow', 'MEDINAN', 1),
    (3, 'آل عمران', "Aal-E-Imran", 'The Family of Imran', 'MEDINAN', 3),
    (4, 'النساء', "An-Nisa", 'The Women', 'MEDINAN', 4),
    (5, 'المائدة', "Al-Ma'idah", 'The Table Spread', 'MEDINAN', 6),
    (6, 'الأنعام', "Al-An'am", 'The Cattle', 'MECCAN', 7),
    (7, 'الأعراف', "Al-A'raf", 'The Heights', 'MECCAN', 8),
    (8, 'الأنفال', 'Al-Anfal', 'The Spoils of War', 'MEDINAN', 9),
    (9, 'التوبة', 'At-Tawbah', 'The Repentance', 'MEDINAN', 10),
    (10, 'يونس', 'Yunus', 'Jonah', 'MECCAN', 11),
    (11, 'هود', 'Hud', 'Hud', 'MECCAN', 11),
    (12, 'يوسف', 'Yusuf', 'Joseph', 'MECCAN', 12),
    (13, 'الرعد', "Ar-Ra'd", 'The Thunder', 'MEDINAN', 13),
    (14, 'إبراهيم', 'Ibrahim', 'Abraham', 'MECCAN', 13),
    (15, 'الحجر', 'Al-Hijr', 'The Rocky Tract', 'MECCAN', 14),
    (16, 'النحل', 'An-Nahl', 'The Bee', 'MECCAN', 14),
    (17, 'الإسراء', "Al-Isra", 'The Night Journey', 'MECCAN', 15),
    (18, 'الكهف', 'Al-Kahf', 'The Cave', 'MECCAN', 15),
    (19, 'مريم', 'Maryam', 'Mary', 'MECCAN', 16),
    (20, 'طه', 'Taha', 'Ta-Ha', 'MECCAN', 16),
    (21, 'الأنبياء', "Al-Anbya", 'The Prophets', 'MECCAN', 17),
    (22, 'الحج', 'Al-Hajj', 'The Pilgrimage', 'MEDINAN', 17),
    (23, 'المؤمنون', "Al-Mu'minun", 'The Believers', 'MECCAN', 18),
    (24, 'النور', 'An-Nur', 'The Light', 'MEDINAN', 18),
    (25, 'الفرقان', 'Al-Furqan', 'The Criterion', 'MECCAN', 18),
    (26, 'الشعراء', "Ash-Shu'ara", 'The Poets', 'MECCAN', 19),
    (27, 'النمل', 'An-Naml', 'The Ant', 'MECCAN', 19),
    (28, 'القصص', 'Al-Qasas', 'The Stories', 'MECCAN', 20),
    (29, 'العنكبوت', "Al-'Ankabut", 'The Spider', 'MECCAN', 20),
    (30, 'الروم', 'Ar-Rum', 'The Romans', 'MECCAN', 21),
    (31, 'لقمان', 'Luqman', 'Luqman', 'MECCAN', 21),
    (32, 'السجدة', 'As-Sajdah', 'The Prostration', 'MECCAN', 21),
    (33, 'الأحزاب', 'Al-Ahzab', 'The Combined Forces', 'MEDINAN', 21),
    (34, 'سبأ', 'Saba', 'Sheba', 'MECCAN', 22),
    (35, 'فاطر', 'Fatir', 'Originator', 'MECCAN', 22),
    (36, 'يس', 'Ya-Sin', 'Ya-Sin', 'MECCAN', 22),
    (37, 'الصافات', 'As-Saffat', 'Those Who Set the Ranks', 'MECCAN', 23),
    (38, 'ص', 'Sad', 'The Letter Sad', 'MECCAN', 23),
    (39, 'الزمر', 'Az-Zumar', 'The Troops', 'MECCAN', 23),
    (40, 'غافر', 'Ghafir', 'The Forgiver', 'MECCAN', 24),
    (41, 'فصلت', 'Fussilat', 'Explained in Detail', 'MECCAN', 24),
    (42, 'الشورى', 'Ash-Shuraa', 'The Consultation', 'MECCAN', 25),
    (43, 'الزخرف', 'Az-Zukhruf', 'The Ornaments of Gold', 'MECCAN', 25),
    (44, 'الدخان', 'Ad-Dukhan', 'The Smoke', 'MECCAN', 25),
    (45, 'الجاثية', 'Al-Jathiyah', 'The Crouching', 'MECCAN', 25),
    (46, 'الأحقاف', 'Al-Ahqaf', 'The Wind-Curved Sandhills', 'MECCAN', 26),
    (47, 'محمد', 'Muhammad', 'Muhammad', 'MEDINAN', 26),
    (48, 'الفتح', 'Al-Fath', 'The Victory', 'MEDINAN', 26),
    (49, 'الحجرات', 'Al-Hujurat', 'The Rooms', 'MEDINAN', 26),
    (50, 'ق', 'Qaf', 'The Letter Qaf', 'MECCAN', 26),
    (51, 'الذاريات', 'Adh-Dhariyat', 'The Winnowing Winds', 'MECCAN', 26),
    (52, 'الطور', 'At-Tur', 'The Mount', 'MECCAN', 27),
    (53, 'النجم', 'An-Najm', 'The Star', 'MECCAN', 27),
    (54, 'القمر', 'Al-Qamar', 'The Moon', 'MECCAN', 27),
    (55, 'الرحمن', 'Ar-Rahman', 'The Beneficent', 'MEDINAN', 27),
    (56, 'الواقعة', "Al-Waqi'ah", 'The Inevitable', 'MECCAN', 27),
    (57, 'الحديد', 'Al-Hadid', 'The Iron', 'MEDINAN', 27),
    (58, 'المجادلة', 'Al-Mujadila', 'The Pleading Woman', 'MEDINAN', 28),
    (59, 'الحشر', 'Al-Hashr', 'The Exile', 'MEDINAN', 28),
    (60, 'الممتحنة', 'Al-Mumtahanah', 'She That Is to Be Examined', 'MEDINAN', 28),
    (61, 'الصف', 'As-Saff', 'The Ranks', 'MEDINAN', 28),
    (62, 'الجمعة', "Al-Jumu'ah", 'The Congregation', 'MEDINAN', 28),
    (63, 'المنافقون', 'Al-Munafiqun', 'The Hypocrites', 'MEDINAN', 28),
    (64, 'التغابن', 'At-Taghabun', 'The Mutual Disillusion', 'MEDINAN', 28),
    (65, 'الطلاق', 'At-Talaq', 'The Divorce', 'MEDINAN', 28),
    (66, 'التحريم', 'At-Tahrim', 'The Prohibition', 'MEDINAN', 28),
    (67, 'الملك', 'Al-Mulk', 'The Sovereignty', 'MECCAN', 29),
    (68, 'القلم', 'Al-Qalam', 'The Pen', 'MECCAN', 29),
    (69, 'الحاقة', 'Al-Haqqah', 'The Reality', 'MECCAN', 29),
    (70, 'المعارج', "Al-Ma'arij", 'The Ascending Stairways', 'MECCAN', 29),
    (71, 'نوح', 'Nuh', 'Noah', 'MECCAN', 29),
    (72, 'الجن', 'Al-Jinn', 'The Jinn', 'MECCAN', 29),
    (73, 'المزمل', 'Al-Muzzammil', 'The Enshrouded One', 'MECCAN', 29),
    (74, 'المدثر', 'Al-Muddaththir', 'The Cloaked One', 'MECCAN', 29),
    (75, 'القيامة', 'Al-Qiyamah', 'The Resurrection', 'MECCAN', 29),
    (76, 'الإنسان', 'Al-Insan', 'Man', 'MEDINAN', 29),
    (77, 'المرسلات', 'Al-Mursalat', 'The Emissaries', 'MECCAN', 29),
    (78, 'النبأ', "An-Naba", 'The Tidings', 'MECCAN', 30),
    (79, 'النازعات', "An-Nazi'at", 'Those Who Drag Forth', 'MECCAN', 30),
    (80, 'عبس', 'Abasa', 'He Frowned', 'MECCAN', 30),
    (81, 'التكوير', 'At-Takwir', 'The Overthrowing', 'MECCAN', 30),
    (82, 'الإنفطار', 'Al-Infitar', 'The Cleaving', 'MECCAN', 30),
    (83, 'المطففين', 'Al-Mutaffifin', 'The Defrauding', 'MECCAN', 30),
    (84, 'الإنشقاق', 'Al-Inshiqaq', 'The Splitting Open', 'MECCAN', 30),
    (85, 'البروج', 'Al-Buruj', 'The Mansions of the Stars', 'MECCAN', 30),
    (86, 'الطارق', 'At-Tariq', 'The Morning Star', 'MECCAN', 30),
    (87, 'الأعلى', "Al-A'la", 'The Most High', 'MECCAN', 30),
    (88, 'الغاشية', 'Al-Ghashiyah', 'The Overwhelming', 'MECCAN', 30),
    (89, 'الفجر', 'Al-Fajr', 'The Dawn', 'MECCAN', 30),
    (90, 'البلد', 'Al-Balad', 'The City', 'MECCAN', 30),
    (91, 'الشمس', 'Ash-Shams', 'The Sun', 'MECCAN', 30),
    (92, 'الليل', 'Al-Layl', 'The Night', 'MECCAN', 30),
    (93, 'الضحى', 'Ad-Duhaa', 'The Morning Hours', 'MECCAN', 30),
    (94, 'الشرح', 'Ash-Sharh', 'The Relief', 'MECCAN', 30),
    (95, 'التين', 'At-Tin', 'The Fig', 'MECCAN', 30),
    (96, 'العلق', "Al-'Alaq", 'The Clot', 'MECCAN', 30),
    (97, 'القدر', 'Al-Qadr', 'The Power', 'MECCAN', 30),
    (98, 'البينة', 'Al-Bayyinah', 'The Clear Proof', 'MEDINAN', 30),
    (99, 'الزلزلة', 'Az-Zalzalah', 'The Earthquake', 'MEDINAN', 30),
    (100, 'العاديات', "Al-'Adiyat", 'The Courser', 'MECCAN', 30),
    (101, 'القارعة', "Al-Qari'ah", 'The Calamity', 'MECCAN', 30),
    (102, 'التكاثر', 'At-Takathur', 'The Rivalry in World Increase', 'MECCAN', 30),
    (103, 'العصر', "Al-'Asr", 'The Declining Day', 'MECCAN', 30),
    (104, 'الهمزة', 'Al-Humazah', 'The Traducer', 'MECCAN', 30),
    (105, 'الفيل', 'Al-Fil', 'The Elephant', 'MECCAN', 30),
    (106, 'قريش', 'Quraysh', 'Quraysh', 'MECCAN', 30),
    (107, 'الماعون', "Al-Ma'un", 'The Small Kindnesses', 'MECCAN', 30),
    (108, 'الكوثر', 'Al-Kawthar', 'The Abundance', 'MECCAN', 30),
    (109, 'الكافرون', 'Al-Kafirun', 'The Disbelievers', 'MECCAN', 30),
    (110, 'النصر', 'An-Nasr', 'The Divine Support', 'MEDINAN', 30),
    (111, 'المسد', 'Al-Masad', 'The Palm Fiber', 'MECCAN', 30),
    (112, 'الإخلاص', 'Al-Ikhlas', 'The Sincerity', 'MECCAN', 30),
    (113, 'الفلق', 'Al-Falaq', 'The Daybreak', 'MECCAN', 30),
    (114, 'الناس', 'An-Nas', 'Mankind', 'MECCAN', 30),
]

# Lookup by surah number
META_BY_NUMBER = {row[0]: row for row in SURAH_META}


def get_meta(number: int):
    """Returns dict with arabic, translation, type, juz, or empty defaults."""
    row = META_BY_NUMBER.get(number)
    if not row:
        return {'arabic': '', 'translation': '', 'type': 'MECCAN', 'juz': 1}
    return {'arabic': row[1], 'transliteration': row[2], 'translation': row[3], 'type': row[4], 'juz': row[5]}
