# Generated by Django 6.0.2 on 2026-02-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dua',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='duas/audio/'),
        ),
    ]
