# Generated by Django 6.0.2 on 2026-02-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duas', '0002_dua_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dua',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
