# Generated by Django 5.0.1 on 2026-02-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duas', '0003_dua_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dua',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='duacategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
