# Generated by Django 6.0.2 on 2026-03-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duas', '0004_alter_dua_slug_alter_duacategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dua',
            name='title_sw',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dua',
            name='translation_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duacategory',
            name='name_sw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
