# Generated by Django 5.0.1 on 2026-04-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duas', '0005_dua_title_sw_dua_translation_sw_duacategory_name_sw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dua',
            name='title_sw',
        ),
        migrations.RemoveField(
            model_name='dua',
            name='translation_sw',
        ),
        migrations.RemoveField(
            model_name='duacategory',
            name='name_sw',
        ),
    ]
