# Generated by Django 5.0.1 on 2026-05-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duas', '0006_remove_dua_title_sw_remove_dua_translation_sw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dhikr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('arabic_text', models.TextField()),
                ('translation', models.TextField()),
                ('default_target', models.PositiveIntegerField(default=33)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
