# Generated by Django 5.0.1 on 2026-02-19 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HadithEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_native', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('edition_key', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Hadith Edition',
                'verbose_name_plural': 'Hadith Editions',
            },
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadith_number', models.CharField(max_length=20)),
                ('arabic_number', models.CharField(blank=True, max_length=20)),
                ('text', models.TextField()),
                ('section', models.CharField(blank=True, max_length=255)),
                ('grades', models.JSONField(blank=True, default=list)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiths', to='hadiths.hadithedition')),
            ],
            options={
                'verbose_name': 'Hadith',
                'verbose_name_plural': 'Hadiths',
                'indexes': [models.Index(fields=['hadith_number'], name='hadiths_had_hadith__5df4fa_idx'), models.Index(fields=['edition'], name='hadiths_had_edition_67c6c2_idx')],
            },
        ),
    ]
