# Generated by Django 6.0.2 on 2026-02-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='icon',
            field=models.CharField(default='bi-folder', help_text='Bootstrap icon class (e.g., bi-book)', max_length=50),
        ),
    ]
