# Generated by Django 6.0.2 on 2026-03-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_podcast_podcastepisode_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranSurah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.PositiveIntegerField()),
                ('surah_name', models.CharField(max_length=200)),
                ('surah_name_arabic', models.CharField(blank=True, max_length=200)),
                ('juz_number', models.PositiveIntegerField()),
                ('juz_name', models.CharField(blank=True, help_text='Optional name for the Juz (e.g. Amma)', max_length=200)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='quran/audio/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='quran/pdfs/')),
                ('reciter', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quran Surah',
                'verbose_name_plural': 'Quran Surahs',
                'ordering': ['surah_number'],
            },
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='episode_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='season_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/videos/'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to YouTube or Vimeo video'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/episodes/'),
        ),
    ]
