# Generated by Django 6.0.2 on 2026-03-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Direct link to remote MP3 (e.g., from archive.org)'),
        ),
    ]
