# Generated by Django 5.0.1 on 2026-04-06 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_podcastepisode_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.PositiveIntegerField(default=1)),
                ('ayah_number', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('translation', models.TextField()),
                ('reference', models.CharField(blank=True, help_text='e.g. 3:8', max_length=100)),
                ('is_daily', models.BooleanField(default=False, help_text="Set as today's Ayah")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='content.quransurah')),
            ],
            options={
                'verbose_name_plural': 'Ayahs',
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('video_file', models.FileField(upload_to='clips/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='clips/thumbnails/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='content.contentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(upload_to='series/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='content.contentcategory')),
            ],
        ),
    ]
